name: Build and Test Anomaly detection commandline tool
on:
  push:
    branches:
      - master
      - opendistro-*
  pull_request:
    branches:
      - master
      - opendistro-*
jobs:
  build:
    strategy:
      matrix:
        platform: [ubuntu-latest, macos-latest, windows-latest]
        go-version: [1.14]
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Set up Go ${{ matrix.platform }}
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}

      - name: Check out AD CLI
        uses: actions/checkout@v2

      - name: Build
        env:
          GOPROXY: "https://proxy.golang.org"
        run: go build .

  code-analysis:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go ubuntu-latest
        uses: actions/setup-go@v2
        with:
          go-version: 1.14

      - name: Check out AD CLI
        uses: actions/checkout@v2

      - name: gofmt
        run: gofmt -s -w .
      - name: Check for modified files
        id: git-check
        run: |
          echo ::set-output name=modified::$(if git diff-index --quiet HEAD --; then echo "false"; else echo "true"; fi)

      - uses: actions/checkout@v2
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v1
        with:
          version: v1.28

      - name: Run coverage
        env:
          GOPROXY: "https://proxy.golang.org"
        run: |
          go test ./...  -coverprofile=coverage.out
          go tool cover -func=coverage.out